version: '3.8'

services:
  stockanal_sys:
    build: .
    ports:
      - '8888:8888'
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=web_server.py
      - PYTHONPATH=/app
      - SKIP_INITIAL_DOWNLOAD=true  # 跳过启动时的股票下载
    volumes:
      - sqlite_data:/app/data # 如果需要持久化数据，请使用sqlite_data 在env文件中设置USE_DATABASE=True
      - .env:/app/.env # 环境变量.env文件
      - ./:/app # 使用相对路径，确保代码同步
      - /app/__pycache__ # 排除Python缓存文件
      - /app/.git # 排除git目录
    depends_on:
      - redis
    # 使用新的启动脚本，快速启动
    command: ['python', 'start_app.py']
    networks:
      - stockanal_network
  
  # redis 缓存 - 使用简化的本地构建
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.simple
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - stockanal_network

networks:
  stockanal_network:
    driver: bridge

volumes:
  redis_data:
  sqlite_data:
